# Generated by Django 4.1.7 on 2023-03-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntheticPlayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=40)),
            ],
        ),
    ]
