# Generated by Django 4.1.7 on 2023-03-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntheticPlayer', '0003_syntheticplayer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticplayer',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
