# Generated by Django 4.1.7 on 2023-04-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syntheticPlayer', '0004_alter_syntheticplayer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntheticplayer',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='syntheticPlayer.categories'),
        ),
        migrations.AlterField(
            model_name='syntheticplayer',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True),
        ),
    ]
