# Generated by Django 4.2 on 2023-04-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntheticPlayer', '0005_syntheticplayer_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticplayer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
