# Generated by Django 4.2 on 2023-04-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syntheticPlayer', '0006_alter_syntheticplayer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='syntheticplayer',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Subscriptions', to='syntheticPlayer.categories'),
        ),
        migrations.AlterField(
            model_name='syntheticplayer',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
