# Generated by Django 4.2 on 2023-04-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntheticPlayer', '0008_remove_syntheticplayer_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntheticplayer',
            name='isHome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='syntheticplayer',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
